/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type CodepenBlock = {
  _type: "codepenBlock";
  codepenUrl: string;
};

export type JsTipsContent = Array<{
  _key: string;
} & HeadingBlock | {
  _key: string;
} & ParagraphBlock | {
  _key: string;
} & QuoteBlock | {
  _key: string;
} & BreakBlock | {
  _key: string;
} & CodeBlock>;

export type Jstips = {
  _id: string;
  _type: "jstips";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  content?: JsTipsContent;
  seo?: SeoFields;
};

export type CodeBlock = {
  _type: "codeBlock";
  code: string;
  language?: "js" | "css" | "bash" | "shell" | "sh" | "html" | "ts";
};

export type BreakBlock = {
  _type: "breakBlock";
  type: "dots" | "line";
};

export type ListBlock = {
  _type: "listBlock";
  style?: "bullet" | "number";
  items?: Array<{
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        openInNewTab?: boolean;
        _type: "anchor";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nestedList?: {
      style?: "bullet" | "number";
      items?: Array<{
        text: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            openInNewTab?: boolean;
            _type: "anchor";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "nestedListItem";
        _key: string;
      }>;
    };
    _type: "listItem";
    _key: string;
  }>;
};

export type ImageBlock = {
  _type: "imageBlock";
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  caption?: string;
  gapBetweenImages?: boolean;
  size?: "small" | "medium" | "large";
};

export type TableBlock = {
  _type: "tableBlock";
  name: string;
  showTitle?: boolean;
  description?: string;
  useFirstAsHeader?: boolean;
  rows?: Array<{
    cells?: Array<{
      content: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: "anchor";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      _type: "cell";
      _key: string;
    }>;
    _type: "row";
    _key: string;
  }>;
};

export type BlogContent = Array<{
  _key: string;
} & HeadingBlock | {
  _key: string;
} & ParagraphBlock | {
  _key: string;
} & QuoteBlock | {
  _key: string;
} & TableBlock | {
  _key: string;
} & ImageBlock | {
  _key: string;
} & BreakBlock | {
  _key: string;
} & CodeBlock | {
  _key: string;
} & CodepenBlock>;

export type HeadingBlock = {
  _type: "headingBlock";
  text: string;
  level?: "h2" | "h3";
};

export type ParagraphBlock = {
  _type: "paragraphBlock";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "anchor";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type QuoteBlock = {
  _type: "quoteBlock";
  style: "default" | "info" | "danger" | "warning";
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "anchor";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  bannerImage?: ImageWithAlt;
  description?: string;
  saveAsDraft?: boolean;
  publishedAt?: string;
  content?: BlogContent;
  seo?: SeoFields;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
};

export type MetaTag = {
  _type: "metaTag";
  metaAttributes?: Array<{
    _key: string;
  } & MetaAttribute>;
};

export type MetaAttribute = {
  _type: "metaAttribute";
  key?: string;
  type?: "string" | "image";
  value?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SeoFields = {
  _type: "seoFields";
  robots?: Robots;
  title?: string;
  description?: string;
  metaImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  metaAttributes?: Array<{
    _key: string;
  } & MetaAttribute>;
  keywords?: Array<string>;
  canonicalUrl?: string;
  openGraph?: OpenGraph;
  twitter?: Twitter;
};

export type Twitter = {
  _type: "twitter";
  card?: "summary" | "summary_large_image" | "app" | "player";
  site?: string;
  creator?: string;
  title?: string;
  description?: string;
  imageType?: "upload" | "url";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageUrl?: string;
};

export type OpenGraph = {
  _type: "openGraph";
  url?: string;
  title?: string;
  description?: string;
  siteName?: string;
  type?: "website" | "article" | "profile" | "book" | "music" | "video" | "product";
  imageType?: "upload" | "url";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageUrl?: string;
};

export type Robots = {
  _type: "robots";
  noIndex?: boolean;
  noFollow?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = CodepenBlock | JsTipsContent | Jstips | CodeBlock | BreakBlock | ListBlock | ImageBlock | TableBlock | BlogContent | HeadingBlock | ParagraphBlock | QuoteBlock | Blog | ImageWithAlt | MetaTag | MetaAttribute | SeoFields | Twitter | OpenGraph | Robots | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: BLOGS_QUERY
// Query: *[_type == "blog" && saveAsDraft == false && defined(publishedAt) && publishedAt <= now()]     | order(publishedAt desc) {      ...    }
export type BLOGS_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  bannerImage?: ImageWithAlt;
  description?: string;
  saveAsDraft?: boolean;
  publishedAt?: string;
  content?: BlogContent;
  seo?: SeoFields;
}>;
// Variable: ALL_BLOGS_QUERY
// Query: *[_type == "blog"]     | order(publishedAt desc) {      ...    }
export type ALL_BLOGS_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  bannerImage?: ImageWithAlt;
  description?: string;
  saveAsDraft?: boolean;
  publishedAt?: string;
  content?: BlogContent;
  seo?: SeoFields;
}>;
// Variable: BLOG_QUERY
// Query: *[_type == "blog" && slug.current == $slug][0] {    ...  }
export type BLOG_QUERYResult = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  bannerImage?: ImageWithAlt;
  description?: string;
  saveAsDraft?: boolean;
  publishedAt?: string;
  content?: BlogContent;
  seo?: SeoFields;
} | null;
// Variable: JSTIPS_QUERY
// Query: *[_type == 'jsTips'] | order(publishedAt desc) {    ...  }
export type JSTIPS_QUERYResult = Array<never>;
// Variable: SINGLE_JS_TIP
// Query: *[_type == "jsTips" && slug.current == $slug][0] {    ...  }
export type SINGLE_JS_TIPResult = null;
// Variable: SEO_BLOG_QUERY
// Query: *[_type == "blog" && slug.current == $slug][0] {    seo  }
export type SEO_BLOG_QUERYResult = {
  seo: SeoFields | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"blog\" && saveAsDraft == false && defined(publishedAt) && publishedAt <= now()] \n    | order(publishedAt desc) {\n      ...\n    }\n": BLOGS_QUERYResult;
    "\n  *[_type == \"blog\"] \n    | order(publishedAt desc) {\n      ...\n    }\n": ALL_BLOGS_QUERYResult;
    "\n  *[_type == \"blog\" && slug.current == $slug][0] {\n    ...\n  }": BLOG_QUERYResult;
    "\n  *[_type == 'jsTips'] | order(publishedAt desc) {\n    ...\n  }  \n": JSTIPS_QUERYResult;
    "\n  *[_type == \"jsTips\" && slug.current == $slug][0] {\n    ...\n  }\n": SINGLE_JS_TIPResult;
    "\n  *[_type == \"blog\" && slug.current == $slug][0] {\n    seo\n  }\n": SEO_BLOG_QUERYResult;
  }
}
